### ISSUE TITLE
fix mobile layout 

### ISSUE THREAD

**Issue by alsturm** [ldbv-by/bav4-nomigration#278]
- fix: The main menu is overlapped by Toolbox.

**Comment by EnBakir** [comment]
- After changing from portrait mode into landscape mode and back, there's a white border overlapping the map. Testet on branch master (last pull 22.06.21 19pm) with iPhone XS iOS 14.6. This happens in Google Chrome and Firefox (latest version) but not in Safari. ![image](https://user-images.githubusercontent.com/74424590/122970099-c1c9a800-d38d-11eb-997f-64e46dd8b398.png)

- The icons seem not to be right adjusted (see picture). Happens on all browsers iOS 14.6. 
![Uploading 122970234...]
