### ISSUE TITLE
header layout

### ISSUE THREAD

**Issue by thiloSchlemmer** [ldbv-by/bav4-nomigration#360]
The coat of arms overlaps the toolbox-content, but the opposite should be true.
![image](https://user-images.githubusercontent.com/2117317/125607050-592cfd0a-b567-42a5-93c4-1e788df373a0.png)

**Comment by alsturm** [comment]
![fail](https://user-images.githubusercontent.com/76113751/125616488-883835a7-dedd-4446-aeec-1e91375e4d69.png)

wrong positon of  menu close button .

**Comment by alsturm** [comment]
badges opacity false

**Comment by alsturm** [comment]
no focus search, routing button
