### ISSUE TITLE
npm script "start" failed after update of webpack

### ISSUE THREAD

**Issue by thiloSchlemmer** [ldbv-by/bav4-nomigration#424]
Due to changes in config of Webpack-dev-server the npm script "start" fails with 

**Webpack Dev Server Invalid Options**-Error.

Removing of the 'static'-option in [webpack.config.js ](https://github.com/ldbv-by/bav4-nomigration/blob/master/webpack.config.js) solves the problem.
`devServer: {
		// static: './dist',
		port: port
	}`

see [Webpack-Dev-Server #1501](https://github.com/webpack/webpack-dev-server/issues/1501)

**Comment by taulinger** [comment]
It runs on my machine 😜. 
Which node version is used in this case?

**Comment by thiloSchlemmer** [comment]
node 14.17.3

**Comment by thiloSchlemmer** [comment]
ok...was more a PEBCAK-styled Issue 

npm i solved the problem :)
