### ISSUE TITLE
remove focus from menu tab after closing tray by swipe gesture

### ISSUE THREAD

**Issue by taulinger** [ldbv-by/bav4-nomigration#897]

**Comment by alsturm** [comment]
Suggestions:

- Same size of the points.
- Marker and Objekt-Info point shut be  clickable and open panel with info...
- (May give posiotn also a point )


![Screenshot](https://user-images.githubusercontent.com/76113751/164234409-a13f7ee2-6d99-4188-9c02-8df9b47378d3.png)

![Screenshot1](https://user-images.githubusercontent.com/76113751/164235555-6b0264bd-40af-4e19-beed-3af0374c4ebd.png)
